name: Build Security Testing Framework

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build script
      run: python build_single_file.py --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SecurityTestingFramework-Windows
        path: dist/SecurityTestingFramework.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SecurityTestingFramework.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-portable:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Create portable package
      run: |
        # Download portable Python
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.11.8/python-3.11.8-embed-amd64.zip" -OutFile "python-portable.zip"

        # Create portable directory
        New-Item -ItemType Directory -Path "portable" -Force
        Expand-Archive -Path "python-portable.zip" -DestinationPath "portable/python"

        # Copy framework files
        Copy-Item -Path "src" -Destination "portable/src" -Recurse
        Copy-Item -Path "resources" -Destination "portable/resources" -Recurse
        Copy-Item -Path "launcher.py" -Destination "portable/"
        Copy-Item -Path "config.json" -Destination "portable/"

        # Create launcher batch file
        @"
        @echo off
        echo Starting Security Testing Framework (Portable)...
        cd /d "%~dp0"
        python\python.exe launcher.py %*
        pause
        "@ | Out-File -FilePath "portable/launch.bat" -Encoding ASCII

        # Compress to ZIP
        Compress-Archive -Path "portable/*" -DestinationPath "SecurityTestingFramework-Portable.zip"
      shell: pwsh

    - name: Upload portable artifact
      uses: actions/upload-artifact@v4
      with:
        name: SecurityTestingFramework-Portable
        path: SecurityTestingFramework-Portable.zip